name: Build custom pandoc container

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Produce release note
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './container/version_file.json'

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.REGISTRY }}/wivik/doc-as-code-example:${{ steps.changelog.outputs.tag }},${{ env.REGISTRY }}/wivik/doc-as-code-example:latest"
          labels: "${{ env.REGISTRY }}/wivik/doc-as-code-example:${{ steps.changelog.outputs.tag }},${{ env.REGISTRY }}/wivik/doc-as-code-example:latest"
          file: Containerfile
          context: container
