name: Publish the document

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout content
        uses: actions/checkout@v3

      - name: Produce changelog
        uses: TriPSs/conventional-changelog-action@v3.19.0
        id: revision
        with:
          version-file: './version_file.json'
          output-file: false
          skip-commit: true
          skip-tag: true

      - name: Write changelog
        run: |
          echo "## ${{ steps.revision.outputs.tag }}" > revision.md
          echo "" >> revision.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %h %an %aD %s" >> revision.md
          echo "" >> revision.md
          cat ./content/02-02-revision-content.md >> revision.md
          echo "" >> revision.md
          cat revision.md > ./content/02-02-revision-content.md

      - name: Fetch files in workspace
        id: content-files
        run: echo CONTENT_FILES=$(ls content/00-*.md content/01-*.md content/02-*.md) >> $GITHUB_OUTPUT

      - name: Write epub
        uses: docker://ghcr.io/wivik/doc-as-code-example:latest
        with:
          args: "-o technical-architecture-document.odt --reference-doc=template/reference.odt --resource-path=.:content ${{ steps.content-files.outputs.CONTENT_FILES }} --standalone --toc --filter=filter/plantuml.py"

      - name: Tag release
        uses: TriPSs/conventional-changelog-action@v3.19.0
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: true

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.tag }}
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          files: |
            technical-architecture-document.odt
