name: Publish the document

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout content
        uses: actions/checkout@v3

      - name: Fetch files in workspace
        id: content-files
        run: echo CONTENT_FILES=$(ls content/00-*.md content/01-*.md content/02-*.md) >> $GITHUB_OUTPUT

      - name: Write epub
        uses: docker://ghcr.io/wivik/doc-as-code-example:latest
        with:
          args: "-o technical-architecture-document.odt --reference-doc=template/reference.odt --resource-path=.:content ${{ steps.content-files.outputs.CONTENT_FILES }} --standalone --toc --filter=filter/plantuml.py"

      - name: Upload odt file
        uses: actions/upload-artifact@v3
        with:
          name: odt-file
          path: technical-architecture-document.odt
